import type {
  AgentEvent,
  DaemonEventMetadata,
  DaemonAgentCreateRequest,
  DaemonAgentDeleteRequest,
  DaemonAgentDeleteResponse,
  DaemonAgentMutationResponse,
  DaemonAgentSource,
  DaemonAgentUpdateRequest,
  DaemonGoalScheduleSummary,
  DaemonManagedAgent,
  DaemonPermissionSnapshot,
  DaemonPermissionUpdate,
  DaemonPermissionUpdateResponse,
  DaemonTask,
  DaemonTaskCancelResponse,
  DaemonTaskOutputResponse,
  Session,
} from '@kode/protocol'

export type { DaemonGoalScheduleSummary }

export type ToolPermissionDecision = 'allow_once' | 'allow_always' | 'deny'

export type ToolPermissionInputUpdate = Record<string, unknown>

/**
 * Request-scoped options shared by direct and daemon-backed clients.
 *
 * `clientMessageUuid` is generated by `HttpClient` when omitted. Supplying a
 * stable value lets a caller retry an optimistic user message without creating
 * a second logical prompt.
 */
export type SendMessageOptions = {
  clientMessageUuid?: string
}

/**
 * The client-facing form of a daemon event.
 *
 * Raw `AgentEvent` remains valid for direct/legacy transports. Daemon-backed
 * clients attach correlation metadata when the server opts into its envelope.
 */
export type CorrelatedAgentEvent = AgentEvent & Partial<DaemonEventMetadata>

export type RuntimeStatus = {
  ok: boolean
  transport: 'direct' | 'daemon'
  pid: number | null
  version: string | null
  activeSessions: number | null
}

/**
 * KodeClient is the UI-facing SDK for driving a Kode session.
 *
 * Implementations:
 * - DirectClient: in-process (CLI/VSCode/Desktop main process)
 * - HttpClient: remote (Web, or any client that talks to `apps/server`)
 */
export interface KodeClient {
  /**
   * Send a user message and stream back events until the request completes.
   */
  sendMessage(
    message: string,
    options?: SendMessageOptions,
  ): AsyncGenerator<CorrelatedAgentEvent>

  /**
   * Cancel the active request, if any.
   */
  cancelRequest(): void

  /**
   * Approve an in-flight tool permission request.
   *
   * `toolUseId` maps to the request identifier emitted by the server. In
   * daemon/WS mode this is aligned to the tool_use id when available.
   */
  approveToolUse(
    toolUseId: string,
    options?: {
      decision?: Exclude<ToolPermissionDecision, 'deny'>
      updatedInput?: ToolPermissionInputUpdate | null
    },
  ): Promise<void>

  /**
   * Deny an in-flight tool permission request.
   */
  denyToolUse(
    toolUseId: string,
    reason?: string,
    options?: { updatedInput?: ToolPermissionInputUpdate | null },
  ): Promise<void>

  /**
   * List known sessions for the current workspace.
   */
  listSessions(): Promise<Session[]>

  /**
   * Read backend runtime availability without attaching a live session.
   */
  getRuntimeStatus(): Promise<RuntimeStatus>

  /**
   * Load a session. Implementations may return metadata-only if full message
   * history is not available via a single call.
   */
  loadSession(sessionId: string): Promise<Session>

  /**
   * Archive a session when the implementation supports lifecycle controls.
   * Daemon-backed clients preserve the persisted transcript for recovery.
   */
  deleteSession(sessionId: string): Promise<void>

  /**
   * True when the underlying transport is connected.
   */
  isConnected(): boolean

  /**
   * Disconnect the underlying transport.
   */
  disconnect(): void
}

/**
 * Optional session-aware capabilities exposed by remote clients.
 *
 * This is a separate interface so existing in-process `KodeClient`
 * implementations, including `DirectClient`, remain source compatible.
 */
export interface SessionAwareKodeClient extends KodeClient {
  /** Attach to an existing session and wait for init plus history replay. */
  attachSession(sessionId: string): Promise<void>

  /** Start a new session and return the id announced by its init event. */
  startSession(): Promise<string>

  /** Subscribe to all validated agent events for the attached session. */
  subscribeEvents(listener: (event: CorrelatedAgentEvent) => void): () => void

  /** Return the session id most recently confirmed by the server. */
  getAttachedSessionId(): string | null
}

/**
 * Experimental daemon-only controls for persistent session lifecycle.
 * Kept separate from KodeClient so in-process clients remain source compatible.
 */
export type SessionMetadataUpdate = {
  customTitle?: string | null
  tag?: string | null
  summary?: string | null
  archived?: boolean
}

export type ForkSessionOptions = {
  newSessionId?: string
  beforeUuid?: string
  includeUuid?: boolean
  customTitle?: string | null
  tag?: string | null
  summary?: string | null
}

export interface SessionControlKodeClient {
  updateSessionMetadata(
    sessionId: string,
    update: SessionMetadataUpdate,
  ): Promise<Session>
  forkSession(sessionId: string, options?: ForkSessionOptions): Promise<Session>
}

/** Daemon-only control surface for workspace-scoped background work. */
export type TaskQueryOptions = {
  sessionId?: string
}

export type TaskOutputOptions = TaskQueryOptions & {
  tailLines?: number
}

export interface TaskControlKodeClient {
  listTasks(options?: TaskQueryOptions): Promise<DaemonTask[]>
  getTask(taskId: string, options?: TaskQueryOptions): Promise<DaemonTask>
  getTaskOutput(
    taskId: string,
    options?: TaskOutputOptions,
  ): Promise<DaemonTaskOutputResponse>
  cancelTask(
    taskId: string,
    options?: TaskQueryOptions,
  ): Promise<DaemonTaskCancelResponse>
}

export type GoalScheduleCreateRequest = {
  sessionId: string
  objective: string
  schedule:
    | { kind: 'once'; runAt?: number }
    | { kind: 'interval'; everyMs: number; anchorAt?: number }
}

export type GoalScheduleActionRequest = {
  sessionId: string
  expectedRevision: number
  action: 'pause' | 'resume' | 'cancel'
  reason?: string
}

export interface GoalScheduleControlKodeClient {
  listGoalSchedules(
    options?: TaskQueryOptions,
  ): Promise<DaemonGoalScheduleSummary[]>
  createGoalSchedule(
    request: GoalScheduleCreateRequest,
  ): Promise<DaemonGoalScheduleSummary>
  transitionGoalSchedule(
    scheduleId: string,
    request: GoalScheduleActionRequest,
  ): Promise<DaemonGoalScheduleSummary>
}

/** Daemon-only permission snapshots and explicitly-audited updates. */
export interface PermissionControlKodeClient {
  getPermissions(options?: TaskQueryOptions): Promise<DaemonPermissionSnapshot>
  updatePermissions(args: {
    sessionId?: string
    update: DaemonPermissionUpdate
  }): Promise<DaemonPermissionUpdateResponse>
}

/** Daemon-only CRUD for Kode-owned, runtime-backed Agent definitions. */
export interface AgentControlKodeClient {
  listAgents(): Promise<DaemonManagedAgent[]>
  getAgent(
    agentType: string,
    source: DaemonAgentSource,
  ): Promise<DaemonManagedAgent>
  createAgent(
    request: DaemonAgentCreateRequest,
  ): Promise<DaemonAgentMutationResponse>
  updateAgent(
    agentType: string,
    request: DaemonAgentUpdateRequest,
  ): Promise<DaemonAgentMutationResponse>
  deleteAgent(
    agentType: string,
    request: DaemonAgentDeleteRequest,
  ): Promise<DaemonAgentDeleteResponse>
}
