export const anthropic = [
  {
    model: 'claude-3-5-haiku-latest',
    max_tokens: 8192,
    max_input_tokens: 200000,
    max_output_tokens: 8192,
    input_cost_per_token: 0.0000008,
    output_cost_per_token: 0.000004,
    cache_creation_input_token_cost: 0.00000125,
    cache_read_input_token_cost: 1e-7,
    provider: 'anthropic',
    mode: 'chat',
    supports_function_calling: true,
    supports_vision: true,
    tool_use_system_prompt_tokens: 264,
    supports_assistant_prefill: true,
    supports_prompt_caching: true,
    supports_response_schema: true,
    deprecation_date: '2025-10-01',
    supports_tool_choice: true,
  },
  {
    model: 'claude-3-opus-latest',
    max_tokens: 4096,
    max_input_tokens: 200000,
    max_output_tokens: 4096,
    input_cost_per_token: 0.000015,
    output_cost_per_token: 0.000075,
    cache_creation_input_token_cost: 0.00001875,
    cache_read_input_token_cost: 0.0000015,
    provider: 'anthropic',
    mode: 'chat',
    supports_function_calling: true,
    supports_vision: true,
    tool_use_system_prompt_tokens: 395,
    supports_assistant_prefill: true,
    supports_prompt_caching: true,
    supports_response_schema: true,
    deprecation_date: '2025-03-01',
    supports_tool_choice: true,
  },
  {
    model: 'claude-3-7-sonnet-latest',
    max_tokens: 8192,
    max_input_tokens: 200000,
    max_output_tokens: 8192,
    input_cost_per_token: 0.000003,
    output_cost_per_token: 0.000015,
    cache_creation_input_token_cost: 0.00000375,
    cache_read_input_token_cost: 3e-7,
    provider: 'anthropic',
    mode: 'chat',
    supports_function_calling: true,
    supports_vision: true,
    tool_use_system_prompt_tokens: 159,
    supports_assistant_prefill: true,
    supports_prompt_caching: true,
    supports_response_schema: true,
    deprecation_date: '2025-06-01',
    supports_tool_choice: true,
  },
]
