export const deepseek = [
  {
    model: 'deepseek-reasoner',
    max_tokens: 8192,
    max_input_tokens: 65536,
    max_output_tokens: 8192,
    input_cost_per_token: 5.5e-7,
    input_cost_per_token_cache_hit: 1.4e-7,
    output_cost_per_token: 0.00000219,
    provider: 'deepseek',
    mode: 'chat',
    supports_function_calling: true,
    supports_assistant_prefill: true,
    supports_tool_choice: true,
    supports_prompt_caching: true,
  },
  {
    model: 'deepseek-chat',
    max_tokens: 8192,
    max_input_tokens: 65536,
    max_output_tokens: 8192,
    input_cost_per_token: 2.7e-7,
    input_cost_per_token_cache_hit: 7e-8,
    cache_read_input_token_cost: 7e-8,
    cache_creation_input_token_cost: 0,
    output_cost_per_token: 0.0000011,
    provider: 'deepseek',
    mode: 'chat',
    supports_function_calling: true,
    supports_assistant_prefill: true,
    supports_tool_choice: true,
    supports_prompt_caching: true,
  },
  {
    model: 'deepseek-coder',
    max_tokens: 4096,
    max_input_tokens: 128000,
    max_output_tokens: 4096,
    input_cost_per_token: 1.4e-7,
    input_cost_per_token_cache_hit: 1.4e-8,
    output_cost_per_token: 2.8e-7,
    provider: 'deepseek',
    mode: 'chat',
    supports_function_calling: true,
    supports_assistant_prefill: true,
    supports_tool_choice: true,
    supports_prompt_caching: true,
  },
]
