export const gemini = [
  {
    model: 'gemini-2.0-flash',
    max_tokens: 8192,
    max_input_tokens: 1048576,
    max_output_tokens: 8192,
    max_images_per_prompt: 3000,
    max_videos_per_prompt: 10,
    max_video_length: 1,
    max_audio_length_hours: 8.4,
    max_audio_per_prompt: 1,
    max_pdf_size_mb: 30,
    input_cost_per_audio_token: 7e-7,
    input_cost_per_token: 0.0000001,
    output_cost_per_token: 0.0000004,
    provider: 'gemini',
    mode: 'chat',
    rpm: 10000,
    tpm: 10000000,
    supports_system_messages: true,
    supports_function_calling: true,
    supports_vision: true,
    supports_response_schema: true,
    supports_audio_output: true,
    supports_tool_choice: true,
    source: 'https://ai.google.dev/pricing#2_0flash',
  },
  {
    model: 'gemini-2.0-flash-lite',
    max_tokens: 8192,
    max_input_tokens: 1048576,
    max_output_tokens: 8192,
    max_images_per_prompt: 3000,
    max_videos_per_prompt: 10,
    max_video_length: 1,
    max_audio_length_hours: 8.4,
    max_audio_per_prompt: 1,
    max_pdf_size_mb: 30,
    input_cost_per_audio_token: 7.5e-8,
    input_cost_per_token: 0.000000075,
    output_cost_per_token: 0.0000003,
    provider: 'gemini',
    mode: 'chat',
    rpm: 60000,
    tpm: 10000000,
    supports_system_messages: true,
    supports_function_calling: true,
    supports_vision: true,
    supports_response_schema: true,
    supports_audio_output: false,
    supports_tool_choice: true,
    source:
      'https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#gemini-2.0-flash-lite',
  },
  {
    model: 'gemini-2.0-flash-thinking-exp',
    max_tokens: 8192,
    max_input_tokens: 1048576,
    max_output_tokens: 8192,
    max_images_per_prompt: 3000,
    max_videos_per_prompt: 10,
    max_video_length: 1,
    max_audio_length_hours: 8.4,
    max_audio_per_prompt: 1,
    max_pdf_size_mb: 30,
    input_cost_per_image: 0,
    input_cost_per_video_per_second: 0,
    input_cost_per_audio_per_second: 0,
    input_cost_per_token: 0,
    input_cost_per_character: 0,
    input_cost_per_token_above_128k_tokens: 0,
    input_cost_per_character_above_128k_tokens: 0,
    input_cost_per_image_above_128k_tokens: 0,
    input_cost_per_video_per_second_above_128k_tokens: 0,
    input_cost_per_audio_per_second_above_128k_tokens: 0,
    output_cost_per_token: 0,
    output_cost_per_character: 0,
    output_cost_per_token_above_128k_tokens: 0,
    output_cost_per_character_above_128k_tokens: 0,
    provider: 'gemini',
    mode: 'chat',
    supports_system_messages: true,
    supports_function_calling: true,
    supports_vision: true,
    supports_response_schema: true,
    supports_audio_output: true,
    tpm: 4000000,
    rpm: 10,
    source:
      'https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models#gemini-2.0-flash',
    supports_tool_choice: true,
  },
]
