export const groq = [
  {
    model: 'llama-3.3-70b-versatile',
    max_tokens: 8192,
    max_input_tokens: 128000,
    max_output_tokens: 8192,
    input_cost_per_token: 5.9e-7,
    output_cost_per_token: 7.9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama2-70b-4096',
    max_tokens: 4096,
    max_input_tokens: 4096,
    max_output_tokens: 4096,
    input_cost_per_token: 7e-7,
    output_cost_per_token: 8e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama3-8b-8192',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 5e-8,
    output_cost_per_token: 8e-8,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.2-1b-preview',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 4e-8,
    output_cost_per_token: 4e-8,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.2-3b-preview',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 6e-8,
    output_cost_per_token: 6e-8,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.2-11b-text-preview',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 1.8e-7,
    output_cost_per_token: 1.8e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.2-90b-text-preview',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 9e-7,
    output_cost_per_token: 9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama3-70b-8192',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 5.9e-7,
    output_cost_per_token: 7.9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.1-8b-instant',
    max_tokens: 8000,
    max_input_tokens: 8000,
    max_output_tokens: 8000,
    input_cost_per_token: 5e-8,
    output_cost_per_token: 8e-8,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.1-70b-versatile',
    max_tokens: 8000,
    max_input_tokens: 8000,
    max_output_tokens: 8000,
    input_cost_per_token: 5.9e-7,
    output_cost_per_token: 7.9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama-3.1-405b-reasoning',
    max_tokens: 8000,
    max_input_tokens: 8000,
    max_output_tokens: 8000,
    input_cost_per_token: 5.9e-7,
    output_cost_per_token: 7.9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'mixtral-8x7b-32768',
    max_tokens: 32768,
    max_input_tokens: 32768,
    max_output_tokens: 32768,
    input_cost_per_token: 2.4e-7,
    output_cost_per_token: 2.4e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'gemma-7b-it',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 7e-8,
    output_cost_per_token: 7e-8,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'gemma2-9b-it',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 2e-7,
    output_cost_per_token: 2e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama3-groq-70b-8192-tool-use-preview',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 8.9e-7,
    output_cost_per_token: 8.9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
  {
    model: 'llama3-groq-8b-8192-tool-use-preview',
    max_tokens: 8192,
    max_input_tokens: 8192,
    max_output_tokens: 8192,
    input_cost_per_token: 1.9e-7,
    output_cost_per_token: 1.9e-7,
    provider: 'groq',
    mode: 'chat',
    supports_function_calling: true,
    supports_response_schema: true,
    supports_tool_choice: true,
  },
]
