export const mistral = [
  {
    model: 'mistral-small',
    max_tokens: 8191,
    max_input_tokens: 32000,
    max_output_tokens: 8191,
    input_cost_per_token: 0.000001,
    output_cost_per_token: 0.000003,
    provider: 'mistral',
    supports_function_calling: true,
    mode: 'chat',
    supports_assistant_prefill: true,
    supports_tool_choice: true,
  },
  {
    model: 'mistral-small-latest',
    max_tokens: 8191,
    max_input_tokens: 32000,
    max_output_tokens: 8191,
    input_cost_per_token: 0.000001,
    output_cost_per_token: 0.000003,
    provider: 'mistral',
    supports_function_calling: true,
    mode: 'chat',
    supports_assistant_prefill: true,
    supports_tool_choice: true,
  },
  {
    model: 'mistral-large-latest',
    max_tokens: 128000,
    max_input_tokens: 128000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000002,
    output_cost_per_token: 0.000006,
    provider: 'mistral',
    mode: 'chat',
    supports_function_calling: true,
    supports_assistant_prefill: true,
    supports_tool_choice: true,
  },
  {
    model: 'open-mixtral-8x7b',
    max_tokens: 8191,
    max_input_tokens: 32000,
    max_output_tokens: 8191,
    input_cost_per_token: 7e-7,
    output_cost_per_token: 7e-7,
    provider: 'mistral',
    mode: 'chat',
    supports_function_calling: true,
    supports_assistant_prefill: true,
    supports_tool_choice: true,
  },
  {
    model: 'open-mixtral-8x22b',
    max_tokens: 8191,
    max_input_tokens: 65336,
    max_output_tokens: 8191,
    input_cost_per_token: 0.000002,
    output_cost_per_token: 0.000006,
    provider: 'mistral',
    mode: 'chat',
    supports_function_calling: true,
    supports_assistant_prefill: true,
    supports_tool_choice: true,
  },
]
