export const openai = [
  {
    model: 'gpt-5.6',
    max_tokens: 128000,
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.00003,
    cache_read_input_token_cost: 0.0000005,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-5.6-sol',
    max_tokens: 128000,
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.00003,
    cache_read_input_token_cost: 0.0000005,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-5.6-terra',
    max_tokens: 128000,
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.000015,
    cache_read_input_token_cost: 0.00000025,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-5.6-luna',
    max_tokens: 128000,
    max_input_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000001,
    output_cost_per_token: 0.000006,
    cache_read_input_token_cost: 0.0000001,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-4',
    max_tokens: 4096,
    max_input_tokens: 8192,
    max_output_tokens: 4096,
    input_cost_per_token: 0.00003,
    output_cost_per_token: 0.00006,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4o',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    input_cost_per_token_batches: 0.00000125,
    output_cost_per_token_batches: 0.000005,
    cache_read_input_token_cost: 0.00000125,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4.5-preview',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.000075,
    output_cost_per_token: 0.00015,
    input_cost_per_token_batches: 0.0000375,
    output_cost_per_token_batches: 0.000075,
    cache_read_input_token_cost: 0.0000375,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4.5-preview-2025-02-27',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.000075,
    output_cost_per_token: 0.00015,
    input_cost_per_token_batches: 0.0000375,
    output_cost_per_token_batches: 0.000075,
    cache_read_input_token_cost: 0.0000375,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4o-mini',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 1.5e-7,
    output_cost_per_token: 6e-7,
    input_cost_per_token_batches: 7.5e-8,
    output_cost_per_token_batches: 3e-7,
    cache_read_input_token_cost: 7.5e-8,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4o-mini-2024-07-18',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 1.5e-7,
    output_cost_per_token: 6e-7,
    input_cost_per_token_batches: 7.5e-8,
    output_cost_per_token_batches: 3e-7,
    cache_read_input_token_cost: 7.5e-8,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'o1',
    max_tokens: 100000,
    max_input_tokens: 200000,
    max_output_tokens: 100000,
    input_cost_per_token: 0.000015,
    output_cost_per_token: 0.00006,
    cache_read_input_token_cost: 0.0000075,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_response_schema: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
  },
  {
    model: 'o3-mini',
    max_tokens: 100000,
    max_input_tokens: 200000,
    max_output_tokens: 100000,
    input_cost_per_token: 0.0000011,
    output_cost_per_token: 0.0000044,
    cache_read_input_token_cost: 5.5e-7,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: false,
    supports_vision: false,
    supports_prompt_caching: true,
    supports_response_schema: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
  },
  {
    model: 'o3-mini-2025-01-31',
    max_tokens: 100000,
    max_input_tokens: 200000,
    max_output_tokens: 100000,
    input_cost_per_token: 0.0000011,
    output_cost_per_token: 0.0000044,
    cache_read_input_token_cost: 5.5e-7,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: false,
    supports_vision: false,
    supports_prompt_caching: true,
    supports_response_schema: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
  },
  {
    model: 'o1-2024-12-17',
    max_tokens: 100000,
    max_input_tokens: 200000,
    max_output_tokens: 100000,
    input_cost_per_token: 0.000015,
    output_cost_per_token: 0.00006,
    cache_read_input_token_cost: 0.0000075,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_response_schema: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
  },
  {
    model: 'chatgpt-4o-latest',
    max_tokens: 4096,
    max_input_tokens: 128000,
    max_output_tokens: 4096,
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.000015,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4o-2024-05-13',
    max_tokens: 4096,
    max_input_tokens: 128000,
    max_output_tokens: 4096,
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.000015,
    input_cost_per_token_batches: 0.0000025,
    output_cost_per_token_batches: 0.0000075,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4o-2024-08-06',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    input_cost_per_token_batches: 0.00000125,
    output_cost_per_token_batches: 0.000005,
    cache_read_input_token_cost: 0.00000125,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4o-2024-11-20',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    input_cost_per_token_batches: 0.00000125,
    output_cost_per_token_batches: 0.000005,
    cache_read_input_token_cost: 0.00000125,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_response_schema: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  {
    model: 'gpt-4-turbo',
    max_tokens: 4096,
    max_input_tokens: 128000,
    max_output_tokens: 4096,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00003,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
  },
  // GPT-5 Models
  {
    model: 'gpt-5',
    max_tokens: 32768,
    max_input_tokens: 200000,
    max_output_tokens: 32768,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00005,
    cache_read_input_token_cost: 0.000005,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-5-mini',
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.000001,
    output_cost_per_token: 0.000005,
    cache_read_input_token_cost: 0.0000005,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-5-nano',
    max_tokens: 8192,
    max_input_tokens: 64000,
    max_output_tokens: 8192,
    input_cost_per_token: 0.0000005,
    output_cost_per_token: 0.000002,
    cache_read_input_token_cost: 0.00000025,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: false,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: true,
    supports_custom_tools: true,
    supports_allowed_tools: true,
    supports_verbosity_control: true,
  },
  {
    model: 'gpt-5-chat-latest',
    max_tokens: 32768,
    max_input_tokens: 200000,
    max_output_tokens: 32768,
    input_cost_per_token: 0.00001,
    output_cost_per_token: 0.00005,
    cache_read_input_token_cost: 0.000005,
    provider: 'openai',
    mode: 'chat',
    supports_function_calling: true,
    supports_parallel_function_calling: true,
    supports_vision: true,
    supports_prompt_caching: true,
    supports_system_messages: true,
    supports_tool_choice: true,
    supports_reasoning_effort: true,
    supports_responses_api: false,
    supports_custom_tools: false,
    supports_allowed_tools: false,
    supports_verbosity_control: true,
    requires_chat_completions: true,
  },
]
